# Development override - use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
version: '3.8'

services:
  morgan-be:
    build:
      target: dev
    volumes:
      - ./framework:/app/framework
      - ./libraries:/app/libraries
      - ./morgan:/app/morgan
