services:
  migrate:
    image: migrate/migrate
    container_name: morgan-migrate
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations -database 'postgres://user:pass@postgres:5432/morgan_be?sslmode=disable' up
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  seeder:
    image: postgres:15-alpine
    container_name: morgan-seeder
    volumes:
      - ./seeders:/seeders
    environment:
      PGPASSWORD: pass
    command: >
      sh -c "psql -h postgres -U user -d morgan_be -f /seeders/001_initial_data.sql"
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - app-network

  morgan-be:
    build:
      context: ..
      dockerfile: morgan/Dockerfile
    container_name: morgan-be
    ports:
      - "8080:8080"
    environment:
      APP_NAME: morgan
      APP_ENV: local
      APP_PORT: 8080
      APP_POSTGRES_URL: "postgres://user:pass@postgres:5432/morgan_be?sslmode=disable"
      APP_REDIS_ADDRESS: "redis:6379"
      APP_REDIS_PASSWORD: ""
      APP_REDIS_DB: 0
      APP_LOG_LEVEL: debug
      APP_LOG_FORMAT: console
      APP_SERVICE_NAME: morgan
      APP_EXPORTER: stdout
      APP_ENDPOINT: "localhost:4317"
      APP_INSECURE: "true"
      APP_REDIRECTURL: "http://localhost:3000/callback"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      seeder:
        condition: service_completed_successfully
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: morgan_be
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d morgan_be"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: "agent -dev -client=0.0.0.0"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
